# Member
### register(image)
POST http://localhost:8080/login/register
Content-Type: multipart/form-data; boundary=boundary
#X-XSRF-TOKEN: 0b731f6b-dbd9-4780-a040-ed3a1cab0307

--boundary
Content-Disposition: form-data; name="memberDto"
Content-Type: application/json

{
  "username": "youcancel",
  "password": "youcancel",
  "address": "qweqf2",
  "phone": "010-1111-1111",
  "email": "qwf@qwe.com",
  "name": "you"
}

--boundary
Content-Disposition: form-data; name="profileImage"; filename="test.jpeg"
Content-Type: image/jpeg

@/D:/Pictures/test.jpeg
--boundary--


### login
POST http://localhost:8080/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkzMzYyODAsInVzZXJuYW1lIjoieW91Y2FuY2VsMSJ9.tWnyoObtGiXrK3kugE6v0aBoVgRX9bLE5FtbiO3t0_0

{
  "username": "youcancel1",
  "password": "youcancel1"
}

### doublecheck
POST http://localhost:8080/login/doubleCheck?username=qwer555



# Post
### post
POST http://localhost:8080/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkyOTg0MTIsInVzZXJuYW1lIjoicXdlciJ9.JaCA5uiM0yLKk5oL9uYEKoa7iDueuMDkwygz-lRDqng
X-XSRF-TOKEN: 0b731f6b-dbd9-4780-a040-ed3a1cab0307
Content-Type: application/json

{
  "title": "qweqf121131",
  "content": "qweqf111",
  "category": "qweqf121"
}

### getallposts
GET http://localhost:8080/posts

### getpost
GET http://localhost:8080/posts/15

### getposts(auth)
GET http://localhost:8080/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg5NDA4MjQsInVzZXJuYW1lIjoicXdlciJ9.tqan9mtHoaC7ajuh6APdLVVmC7uKUIkyJPAQ8Q6tmfE

### updatepost
PUT http://localhost:8080/post/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg5ODQ1NDIsInVzZXJuYW1lIjoicXdlciJ9.xLkqdNSYDMIzvG6IZupJds-hjk-4ok56NwAi923X-lI
Content-Type: application/json
X-XSRF-TOKEN: 0b731f6b-dbd9-4780-a040-ed3a1cab0307

{
  "title": "112qqq31",
  "content": "1232qq1312",
  "category": "321qqq312"
}

### deletepost
DELETE http://localhost:8080/post/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg5NDA4MjQsInVzZXJuYW1lIjoicXdlciJ9.tqan9mtHoaC7ajuh6APdLVVmC7uKUIkyJPAQ8Q6tmfE



# Comment
### comment
POST http://localhost:8080/comment/4?comment=qwer4534253
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg5NDA4MjQsInVzZXJuYW1lIjoicXdlciJ9.tqan9mtHoaC7ajuh6APdLVVmC7uKUIkyJPAQ8Q6tmfE
Content-Type: application/x-www-form-urlencoded

### getallcomments
GET http://localhost:8080/comments

### getcomment
GET http://localhost:8080/comments/comment/33
Accept: application/json

### getPostComment
GET http://localhost:8080/comments/post/11
Accept: application/json

### updatecomment
PUT http://localhost:8080/comment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgyOTU5MzEsInVzZXJuYW1lIjoicXdlciJ9.2PajwI_1XZJU9ZFb4JIKMnN2_lm7U1fTJhzv8InVwSM
Content-Type: application/json

{
  "comment": "qweqf123"
}

### deletecomment
DELETE http://localhost:8080/comment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgyOTU5MzEsInVzZXJuYW1lIjoicXdlciJ9.2PajwI_1XZJU9ZFb4JIKMnN2_lm7U1fTJhzv8InVwSM


# Report
### Report
POST http://localhost:8080/report/22?reason=feqfeqg
Content-Type: application/x-www-form-urlencoded




### Like
POST http://localhost:8080/like/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgyOTU5MzEsInVzZXJuYW1lIjoicXdlciJ9.2PajwI_1XZJU9ZFb4JIKMnN2_lm7U1fTJhzv8InVwSM

### getlike
GET http://localhost:8080/likes/2


### ML
POST http://localhost:8080/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

@/D:/A/test.jpg
--boundary--

### createChattingRoom
POST http://localhost:8080/chatting/chattingroom?user1=youcancel1&user2=youcancel2
Content-Type: application/json

{
  "title": "Test",
  "content": "Hello"
}